"""
ReconMind — scanner/engine/scan_runner.py

Core scan orchestrator. This is the brain of the Scanner Engine.

Full pipeline:
  PENDING scan picked from DB
       ↓
  DorkEngine   → generate targeted dork queries
       ↓
  Discovery    → execute queries, extract raw URLs
       ↓
  Validator    → check each URL (alive? status code? headers?)
       ↓
  EvidenceStore→ save verified results to DB
       ↓
  Scan marked COMPLETED

Phase 6: AI model will receive completed scan data for analysis.
"""

import asyncio
import uuid
from datetime import datetime, timezone
from typing import List, Optional

from scanner.dork_engine.dork_engine import DorkEngine
from scanner.discovery.discovery import DiscoveryEngine
from scanner.validator.validator import URLValidator
from scanner.evidence.evidence_store import EvidenceStore
from scanner.utils.logger import get_logger
from scanner.utils.models import (
    ScanTask, DorkResult, DiscoveryResult,
    ValidatedURL, ScanStatus
)

logger = get_logger("scan_runner")


class ScanRunner:
    """
    Orchestrates a single scan from start to finish.

    Usage:
        task = ScanTask(
            scan_id="...",
            target="example.com",
            depth="standard",
            dork_categories=["file_exposure", "admin_panels"],
            dorks=[{"category": "...", "query": "..."}],
        )
        runner = ScanRunner(db_url="postgresql+asyncpg://...")
        await runner.run(task)
    """

    def __init__(self, db_url: str):
        self.db_url = db_url
        self.dork_engine = DorkEngine()
        self.discovery = DiscoveryEngine()
        self.validator = URLValidator()
        self.evidence = EvidenceStore(db_url=db_url)

    async def run(self, task: ScanTask) -> dict:
        """
        Execute full scan pipeline for a given ScanTask.
        Returns a summary dict on completion.
        """
        scan_id = task.scan_id
        start_time = datetime.now(timezone.utc)

        logger.info(f"[{scan_id}] ═══ Scan started: {task.target} ═══")

        try:
            # ── Step 1: Mark scan as RUNNING ────────────────
            await self.evidence.update_scan_status(
                scan_id=scan_id,
                status=ScanStatus.RUNNING,
            )
            logger.info(f"[{scan_id}] Step 1/5 — Status: RUNNING")

            # ── Step 2: Generate / load dorks ───────────────
            # If dorks were pre-generated by backend, use them.
            # Otherwise generate fresh ones.
            if task.dorks:
                dorks = task.dorks
                logger.info(f"[{scan_id}] Step 2/5 — Using {len(dorks)} pre-generated dorks")
            else:
                dorks = self.dork_engine.generate(
                    target=task.target,
                    categories=task.dork_categories,
                    depth=task.depth,
                )
                logger.info(f"[{scan_id}] Step 2/5 — Generated {len(dorks)} dorks")

            # ── Step 3: Discovery (execute dork queries) ────
            logger.info(f"[{scan_id}] Step 3/5 — Discovery starting...")
            raw_results: List[DiscoveryResult] = await self.discovery.run(
                scan_id=scan_id,
                dorks=dorks,
                target=task.target,
            )
            logger.info(f"[{scan_id}] Step 3/5 — Discovery found {len(raw_results)} raw URLs")

            # ── Step 4: Validate URLs ───────────────────────
            logger.info(f"[{scan_id}] Step 4/5 — Validating {len(raw_results)} URLs...")
            validated: List[ValidatedURL] = await self.validator.validate_all(raw_results)
            alive_count = sum(1 for v in validated if v.is_alive)
            logger.info(
                f"[{scan_id}] Step 4/5 — Validated: {alive_count}/{len(validated)} alive"
            )

            # ── Step 5: Store evidence ──────────────────────
            logger.info(f"[{scan_id}] Step 5/5 — Storing evidence...")
            stored_count = await self.evidence.store_results(
                scan_id=scan_id,
                results=validated,
            )

            # ── Mark COMPLETED ──────────────────────────────
            elapsed = (datetime.now(timezone.utc) - start_time).total_seconds()
            await self.evidence.update_scan_status(
                scan_id=scan_id,
                status=ScanStatus.COMPLETED,
                total_urls_found=len(raw_results),
                total_findings=alive_count,
            )

            summary = {
                "scan_id": str(scan_id),
                "target": task.target,
                "status": "completed",
                "dorks_used": len(dorks),
                "urls_discovered": len(raw_results),
                "urls_alive": alive_count,
                "results_stored": stored_count,
                "elapsed_seconds": round(elapsed, 2),
            }

            logger.info(
                f"[{scan_id}] ═══ Scan COMPLETED in {elapsed:.1f}s "
                f"| dorks={len(dorks)} | found={len(raw_results)} | alive={alive_count} ═══"
            )
            return summary

        except asyncio.CancelledError:
            logger.warning(f"[{scan_id}] Scan was cancelled.")
            await self.evidence.update_scan_status(
                scan_id=scan_id,
                status=ScanStatus.CANCELLED,
            )
            raise

        except Exception as e:
            logger.error(f"[{scan_id}] Scan FAILED: {e}", exc_info=True)
            await self.evidence.update_scan_status(
                scan_id=scan_id,
                status=ScanStatus.FAILED,
                error_message=str(e),
            )
            return {
                "scan_id": str(scan_id),
                "target": task.target,
                "status": "failed",
                "error": str(e),
            }
